### PR TITLE
Support for Launchpad Pro Mk3

### PR DESCRIPTION
**Pull request by jmsole**
Added support for Launchpad Pro Mk3 based on Launchpad Pro Device files plus modified init code from Launchpad Mk3 Device files.

### CODE REVIEW

**Comment by westlicht** [comment]
@jmsole this looks great. Is it tested and confirmed to work? .. and sorry for the late response!

**Comment by jmsole** [comment]
It's working well for me. I didn't assign any other functionality to the additional buttons the Pro MK3 has, but all the buttons shared between Pros work the same. I'll get your latest changes to my fork in a bit and resolve the conflicts.

**Comment by jmsole** [comment]
@westlicht Merged your change from yesterday so no more conflicts.

**Comment by westlicht** [comment]
merged now, there was an issue with filename upper/lower case, but i've fixed that in master
thanks for the contribution

**Pull request merged**
